import { getVeljvo } from "latkerlo-jvotci";
import jvs from "../lidysisku/jvs-en.json";
import { analyseBrivla } from "./jvotci";

export const definitions: Record<string, string> = {};

for (const row of jvs) {
	if (typeof row[4] === "string") {
		definitions[row[0]] = row[4];
	}
}

export const shortDescriptions: Record<string, string> = {
	e: "and",
	ji: "or?",
	o: "iff",
	a: "or",
	u: "whether or not",

	je: "and",
	"je'i": "or?",
	jo: "iff",
	ja: "or",
	ju: "whether or not",

	joi: "and",

	noi: "which",
	poi: "which",
	voi: "which",

	"je'u": "[truth]",
	"ju'o": "I'm certain",

	// "du'o": "according to",
	// "si'u": "aided by",
	// zau: "approved by",
	// "ki'i": "as a relation of",
	// "du'i": "as much as",
	// "cu'u": "as said by",
	// "tu'i": "associated with site",
	// "ti'u": "associated with time",
	// "di'o": "at the locus of",
	// "ji'u": "based on",
	// "ri'a": "because of cause",
	// "ni'i": "because of logic",
	// "mu'i": "because of motive",
	// "ki'u": "because of reason",
	// "va'u": "benefiting from",
	// koi: "bounded by",
	// "ca'i": "by authority of",
	// "ta'i": "by method",
	// "pu'e": "by process",
	// "ja'i": "by rule",
	// kai: "characterizing",
	// bai: "compelled by",
	// "fi'e": "created by",
	// "de'i": "dated",
	// "ci'o": "emotionally felt by",
	// mau: "exceeded by",
	// "mu'u": "exemplified by",
	// "ri'i": "experienced by",
	// "ra'i": "from source",
	// "ka'a": "gone by",
	// "pa'u": "having component",
	// "pa'a": "in addition to",
	// "le'a": "in category",
	// "ku'u": "in culture",
	// tai: "in form",
	// bau: "in language",
	// "ma'i": "in reference frame",
	// "ci'e": "in system",
	// fau: "in the event of",
	// "po'i": "in the sequence",
	// cau: "lacked by",
	// "ma'e": "material object",
	// "ci'u": "on the scale",
	// "ra'a": "pertained by",
	// "pu'a": "pleased by",
	// "li'e": "preceded by",
	// "la'u": "quantifying",
	// "ba'i": "replaced by",
	// "ka'i": "represented by",
	// sau: "requiring",
	// "fa'e": "reverse of",
	// "be'i": "sent by",
	// "ti'i": "suggested by",
	// "ja'e": "therefore result",
	// "ga'a": "observer",
	// "va'o": "under conditions",
	// "ji'o": "under direction of",
	// "me'a": "undercut by",
	// "do'e": "(unspecified modal)",
	// "ji'e": "up limit",
	// "pi'o": "used by",
	// gau: "with active agent",
	// "zu'e": "with actor",
	// "me'e": "with name",
	// rai: "with superlative",

	/*
    "ga'e": "BY1",
    "ge'o": "BY1",
    "je'o": "BY1",
    "jo'o": "BY1",
    "lo'a": "BY1",
    "na'a": "BY1",
    "ru'o": "BY1",
    "se'e": "BY1",
    "to'a": "BY1",
    
    
    // COI: vocative with meaning
    "coi": "COI",
    "co'o": "COI",
    "je'e": "COI",
    "nu'e": "COI",
    "ju'i": "COI",
    "ta'a": "COI",
    "pe'u": "COI",
    "ki'e": "COI",
    "fi'i": "COI",
    "be'e": "COI",
    "re'i": "COI",
    "mu'o": "COI",
    "vi'o": "COI",
    "ke'o": "COI",
    "fe'o": "COI",
    "mi'e": "COI",
    
    // CU: separate selbri from preceding sumti
    "cu": "CU",
    
    // DOI: vocative without meaning
    "doi": "DOI",
    
    // FEhU: fa'orma'o for FIhO
    "fe'u": "FEhU",
    
    // FIhO: start modal tag
    "fi'o": "FIhO",
    
    // GEhU: fa'orma'o for GOI
    "ge'u": "GEhU",
    
    // GOhA: pro-selbri
    "mo": "GOhA",
    "nei": "GOhA",
    "go'u": "GOhA",
    "go'o": "GOhA",
    "go'i": "GOhA",
    "no'a": "GOhA",
    "go'e": "GOhA",
    "go'a": "GOhA",
    "du": "GOhA",
    "bu'a": "GOhA",
    "bu'e": "GOhA",
    "bu'i": "GOhA",
    "co'e": "GOhA",
    
    // GOI: relative phrase
    "pe": "GOI",
    "po": "GOI",
    "po'e": "GOI",
    "po'u": "GOI",
    "ne": "GOI",
    "no'u": "GOI",
    
    // JOI: non-logical connectives (for all except bridi)
    "ce": "JOI",
    "ce'o": "JOI",
    "fa'u": "JOI",
    "jo'e": "JOI",
    "jo'u": "JOI",
    "joi": "JOI",
    "ju'e": "JOI",
    "ku'a": "JOI",
    "pi'u": "JOI",
    "ce'oi": "JOI",
    
    // KOhA*: sumka'i
    "da": "KOhA1",
    "de": "KOhA1",
    "di": "KOhA1",
    "da'u": "KOhA2",
    "da'e": "KOhA2",
    "di'u": "KOhA2",
    "di'e": "KOhA2",
    "de'u": "KOhA2",
    "de'e": "KOhA2",
    "dei ": "KOhA2",
    "do'i": "KOhA2",
    "ko": "KOhA3",
    "mi": "KOhA3",
    "mi'o": "KOhA3",
    "ma'a": "KOhA3",
    "mi'a": "KOhA3",
    "do": "KOhA3",
    "do'o": "KOhA3",
    "ko'a": "KOhA4",
    "fo'u": "KOhA4",
    "ko'e": "KOhA4",
    "ko'i": "KOhA4",
    "ko'o": "KOhA4",
    "ko'u": "KOhA4",
    "fo'a": "KOhA4",
    "fo'e": "KOhA4",
    "fo'i": "KOhA4",
    "fo'o": "KOhA4",
    "vo'a": "KOhA4",
    "vo'e": "KOhA4",
    "vo'i": "KOhA4",
    "vo'o": "KOhA4",
    "vo'u": "KOhA4",
    "ru": "KOhA5",
    "ri": "KOhA5",
    "ra": "KOhA5",
    "ta": "KOhA6",
    "tu": "KOhA6",
    "ti": "KOhA6",
    "zi'o": "KOhA7",
    "ke'a": "KOhA7",
    "ma": "KOhA7",
    "zu'i": "KOhA7",
    "zo'e": "KOhA7",
    "ce'u": "KOhA8",
    
    // KU: fa'orma'o for LE and unfilled tags
    "ku": "KU",
    
    // KUhO: fa'orma'o for NOI
    "ku'o": "KUhO",
    
    // LA: gadri for names
    "la": "LA",
    "lai": "LA",
    "la'i": "LA",
    
    // LE: gadri for objects
    "le": "LE",
    "lei": "LE",
    "loi": "LE",
    "lo": "LE",
    "le'i": "LE",
    "lo'i": "LE",
    "le'e": "LE",
    "lo'e": "LE",
    
    // LI: gadri for numbers
    "li": "LI",
    "me'o": "LI",
    "li'ai": "LI",
    
    // LIhU: fa'orma'o for LU
    "li'u": "LIhU",
    
    // LU: grammatical quote
    "lu": "LU",
    "la'au": "LU",
    
    // MOI
    "mei": "MOI",
    "moi": "MOI",
    "si'e": "MOI",
    "cu'o": "MOI",
    
    // NOI: relative clauses
    "noi": "NOI",
    "poi": "NOI",
    "voi": "NOI",
    
    // NU: abstractors
    "du'u": "NU",
    "jei": "NU",
    "ka": "NU",
    "jei": "NU",
    "li'i": "NU",
    "mu'e": "NU",
    "ni": "NU",
    "nu": "NU",
    "pu'u": "NU",
    "si'o": "NU",
    "su'u": "NU",
    "za'i": "NU",
    "zu'o": "NU",
    
    "ba": "PU",
    "pu": "PU",
    "ca": "PU",
    
    "se": "SE",
    "te": "SE",
    "ve": "SE",
    "xe": "SE",
    
    // UI: indicators
    
    "ki'a": "UI6",
    "xu": "UI6",
    
    "vi": "VA",
    "va": "VA",
    "vu": "VA",
    
    // ZIhE: join relatives
    "zi'e": "ZIhE",
    
    // ZOI: non-Lojban quotes
    "zoi": "ZOI",
    "la'o": "ZOI",
    
    
    */

	ui: "yay",
	"i'a": "okay",
	ie: "yeah",
	"u'i": "haha",
	"i'o": "thanks",
	"i'e": "good!",
	"a'a": "oh",
	ia: "I believe",
	"o'i": "watch out!",
	"e'e": "can",
	oi: "ugh",
	uo: "there!",
	"e'i": "must",
	au: "want",
	ua: "aha",
	ii: "eek",
	"a'o": "hope",
	ai: "intend",
	"a'u": "ooh",
	iu: "<3",
	ei: "should",
	"e'a": "you may",
	uu: "aw",
	"u'u": "sorry",
	"e'o": "please",
	io: "dear",
	"e'u": "how about",
	ue: "wow",
	"i'i": "same!",
	"u'e": "whoa...",

	se: "x2",
	te: "x3",
	ve: "x4",
	xe: "x5",
	fa: "x1",
	fe: "x2",
	fi: "x3",
	fo: "x4",
	fu: "x5",

	// pro-sumti
	mi: "me",
	do: "you",
	ko: "you!",
	ti: "this",
	ta: "that",
	tu: "that",
	ma: "what",
	"ke'a": "it",

	// vocatives
	coi: "hello",
	doi: "(vocative)",
	"mi'e": "I am",
	"je'e": "okay",
	"co'o": "goodbye",

	// tenses
	pu: "did",
	ca: "now",
	ba: "will",

	// abstractors
	"du'u": "that",
	nu: "event of",

	// numbers
	pa: "1",
	re: "2",
	ci: "3",
	vo: "4",
	mu: "5",
	xa: "6",
	ze: "7",
	bi: "8",
	so: "9",
	no: "0",
	ro: "all",
	"su'o": "some",

	"zo'e": "something",
	na: "not",
	nai: "not",
	xu: "if?",

	// pro-selbri
	du: "equal",
	mo: "is what?",

	// gismu
	bacru: "utter",
	badna: "banana",
	badri: "sad",
	bajra: "run",
	bakfu: "bundle",
	bakni: "bovine",
	bakri: "chalk",
	baktu: "bucket",
	balji: "bulb",
	balni: "balcony",
	balre: "blade",
	balvi: "future",
	bancu: "beyond",
	bandu: "defend",
	banfi: "amphibian",
	bangu: "language",
	banli: "great",
	banro: "grow",
	banxa: "bank",
	banzu: "suffice",
	bapli: "force",
	barda: "big",
	bargu: "arch",
	barja: "bar",
	barna: "mark",
	bartu: "out",
	basna: "emphasize",
	basti: "replace",
	batci: "bite",
	batke: "button",
	bavmi: "barley",
	baxso: "Malay-Indonesian",
	bebna: "foolish",
	bemro: "North American",
	bende: "crew",
	bengo: "Bengali",
	benji: "transfer",
	bersa: "son",
	berti: "north",
	besna: "brain",
	betfu: "abdomen",
	betri: "tragedy",
	bevri: "carry",
	bidju: "bead",
	bifce: "bee",
	bikla: "whip",
	bilga: "obliged",
	bilma: "ill",
	bilni: "military",
	bindo: "Indonesian",
	binra: "insure",
	binxo: "become",
	birje: "beer",
	birka: "arm",
	birti: "certain",
	bisli: "ice",
	bitmu: "wall",
	blabi: "white",
	blaci: "glass",
	blanu: "blue",
	bliku: "block",
	bloti: "boat",
	bolci: "ball",
	bongu: "bone",
	botpi: "bottle",
	boxfo: "sheet",
	boxna: "wave",
	bradi: "enemy",
	bratu: "hail",
	brazo: "Brazilian",
	bredi: "ready",
	bridi: "predicate",
	brife: "breeze",
	briju: "office",
	brito: "British",
	broda: "(predicate variable 1)",
	brode: "(predicate variable 2)",
	brodi: "(predicate variable 3)",
	brodo: "(predicate variable 4)",
	brodu: "(predicate variable 5)",
	bruna: "brother",
	budjo: "Buddhist",
	bukpu: "cloth",
	bumru: "fog",
	bunda: "pound",
	bunre: "brown",
	burcu: "brush",
	burna: "embarrassed",
	cabna: "now",
	cabra: "apparatus",
	cacra: "hour",
	cadzu: "walk",
	cafne: "often",
	cakla: "chocolate",
	calku: "shell",
	canci: "vanish",
	cando: "idle",
	cange: "farm",
	canja: "exchange",
	canko: "window",
	canlu: "space",
	canpa: "shovel",
	canre: "sand",
	canti: "gut",
	carce: "cart",
	carmi: "intense",
	carna: "turn",
	cartu: "chart",
	carvi: "rain",
	casnu: "discuss",
	catke: "shove",
	catlu: "look",
	catni: "authority",
	catra: "kill",
	caxno: "shallow",
	cecla: "launcher",
	cecmu: "community",
	cedra: "era",
	cenba: "vary",
	censa: "holy",
	centi: ".01",
	cerda: "heir",
	cerni: "morning",
	certu: "expert",
	cevni: "god",
	cfari: "initiate",
	cfika: "fiction",
	cfila: "flaw",
	cfine: "wedge",
	cfipu: "confusing",
	ciblu: "blood",
	cicna: "cyan",
	cidja: "food",
	cidni: "knee",
	cidro: "hydrogen",
	cifnu: "infant",
	cigla: "gland",
	cikna: "awake",
	cikre: "repair",
	ciksi: "explain",
	cilce: "wild",
	cilmo: "moist",
	cilre: "learn",
	cilta: "thread",
	cimde: "dimension",
	cimni: "infinite",
	cinba: "kiss",
	cindu: "oak",
	cinfo: "lion",
	cinje: "wrinkle",
	cinki: "insect",
	cinla: "thin",
	cinmo: "emotion",
	cinri: "interesting",
	cinse: "sexual",
	cinta: "paint",
	cinza: "tongs",
	cipni: "bird",
	cipra: "test",
	cirko: "lose",
	cirla: "cheese",
	ciska: "write",
	cisma: "smile",
	ciste: "system",
	citka: "eat",
	citno: "young",
	citri: "history",
	citsi: "season",
	civla: "louse",
	cizra: "strange",
	ckabu: "rubber",
	ckafi: "coffee",
	ckaji: "quality",
	ckana: "bed",
	ckape: "peril",
	ckasu: "ridicule",
	ckeji: "ashamed",
	ckiku: "key",
	ckilu: "scale",
	ckini: "related",
	ckire: "grateful",
	ckule: "school",
	ckunu: "conifer",
	cladu: "loud",
	clani: "long",
	claxu: "without",
	clika: "mossy",
	clira: "early",
	clite: "polite",
	cliva: "leave",
	clupa: "loop",
	cmaci: "mathematics",
	cmalu: "small",
	cmana: "mountain",
	cmavo: "(Lojban) cmavo",
	cmene: "name",
	cmila: "laugh",
	cmima: "member",
	cmoni: "moan",
	cnano: "norm",
	cnebo: "neck",
	cnemu: "reward",
	cnici: "orderly",
	cnino: "new",
	cnisa: "lead",
	cnita: "beneath",
	cokcu: "soak up",
	condi: "deep",
	cortu: "pain",
	cpacu: "get",
	cpana: "upon",
	cpare: "climb",
	cpedu: "request",
	cpina: "pungent",
	cradi: "radio",
	crane: "front",
	creka: "shirt",
	crepu: "harvest",
	cribe: "bear",
	crida: "fairy",
	crino: "green",
	cripu: "bridge",
	crisa: "summer",
	critu: "autumn",
	ctaru: "tide",
	ctebi: "lip",
	cteki: "tax",
	ctile: "petroleum",
	ctino: "shadow",
	ctuca: "teach",
	cukla: "round",
	cukta: "book",
	culno: "full",
	cumki: "possible",
	cumla: "humble",
	cunmi: "millet",
	cunso: "random",
	cuntu: "affair",
	cupra: "produce",
	curmi: "permit",
	curnu: "worm",
	curve: "pure",
	cusku: "say",
	cutci: "shoe",
	cutne: "chest",
	cuxna: "choose",
	dacru: "drawer",
	dacti: "object",
	dadjo: "Taoist",
	dakfu: "knife",
	dakli: "sack",
	damba: "fight",
	damri: "drum",
	dandu: "hang",
	danfu: "answer",
	danlu: "animal",
	danmo: "smoke",
	danre: "pressure",
	dansu: "dance",
	danti: "projectile",
	daplu: "island",
	dapma: "curse",
	dargu: "road",
	darlu: "argue",
	darno: "far",
	darsi: "audacity",
	darxi: "hit",
	daski: "pocket",
	dasni: "wear",
	daspo: "destroy",
	dasri: "ribbon",
	datka: "duck",
	datni: "data",
	decti: "0.1",
	degji: "finger",
	dejni: "owe",
	dekpu: "gallon",
	dekto: "10",
	delno: "candela",
	dembi: "bean",
	denci: "tooth",
	denmi: "dense",
	denpa: "wait",
	dertu: "dirt",
	derxi: "heap",
	desku: "shake",
	detri: "date",
	dicra: "interrupt",
	dikca: "electric",
	diklo: "local",
	dikni: "regular",
	dilcu: "quotient",
	dilnu: "cloud",
	dimna: "fate",
	dinju: "building",
	dinko: "nail",
	dirba: "dear",
	dirce: "radiate",
	dirgo: "drop",
	dizlo: "low",
	djacu: "water",
	djedi: "day",
	djica: "want",
	djine: "ring",
	djuno: "know",
	donri: "daytime",
	dotco: "German",
	draci: "drama",
	drani: "correct",
	drata: "other",
	drudi: "roof",
	dugri: "logarithm",
	dukse: "excess",
	dukti: "opposite",
	dunda: "give",
	dunja: "freeze",
	dunku: "stressed",
	dunli: "equal",
	dunra: "winter",
	dzena: "elder",
	dzipo: "Antarctic",
	facki: "discover",
	fadni: "ordinary",
	fagri: "fire",
	falnu: "sail",
	famti: "aunt; uncle",
	fancu: "function",
	fange: "alien",
	fanmo: "end",
	fanri: "factory",
	fanta: "prevent",
	fanva: "translate",
	fanza: "annoy",
	fapro: "oppose",
	farlu: "fall",
	farna: "direction",
	farvi: "develop",
	fasnu: "event",
	fatci: "fact",
	fatne: "reverse",
	fatri: "distribute",
	febvi: "boil",
	// femti: "1e-15",
	fendi: "divide",
	fengu: "angry",
	fenki: "crazy",
	fenra: "crack",
	fenso: "sew",
	fepni: "cent",
	fepri: "lung",
	ferti: "fertile",
	festi: "waste",
	fetsi: "female",
	figre: "fig",
	filso: "Palestinian",
	finpe: "fish",
	finti: "invent",
	flalu: "law",
	flani: "flute",
	flecu: "flow",
	fliba: "fail",
	flira: "face",
	foldi: "field",
	fonmo: "foam",
	fonxa: "telephone",
	forca: "fork",
	fraso: "French",
	frati: "react",
	fraxu: "forgive",
	frica: "differ",
	friko: "African",
	frili: "easy",
	frinu: "fraction",
	friti: "offer",
	frumu: "frown",
	fukpi: "copy",
	fulta: "float",
	funca: "luck",
	fusra: "rotten",
	fuzme: "responsible",
	gacri: "cover",
	gadri: "article",
	galfi: "modify",
	galtu: "high",
	galxe: "throat",
	ganlo: "closed",
	ganra: "broad",
	ganse: "sense",
	ganti: "gonad",
	ganxo: "anus",
	ganzu: "organize",
	gapci: "gas",
	gapru: "above",
	garna: "rail",
	gasnu: "do",
	gasta: "steel",
	genja: "root",
	gento: "Argentinian",
	genxu: "hook",
	gerku: "dog",
	gerna: "grammar",
	gidva: "guide",
	// gigdo: "1e9",
	ginka: "camp",
	girzu: "group",
	gismu: "gismu",
	glare: "hot",
	gleki: "happy",
	gletu: "copulate",
	glico: "English",
	gluta: "glove",
	// gocti: "1e-24",
	// gotro: "1e24",
	gradu: "unit",
	grake: "gram",
	grana: "rod",
	grasu: "grease",
	greku: "frame",
	grusi: "gray",
	grute: "fruit",
	gubni: "public",
	gugde: "country",
	gundi: "industry",
	gunka: "work",
	gunma: "jointly",
	gunro: "roll",
	gunse: "goose",
	gunta: "attack",
	gurni: "grain",
	guska: "scrape",
	gusni: "light",
	gusta: "restaurant",
	gutci: "cubit",
	gutra: "womb",
	guzme: "melon",
	jabre: "brake",
	jadni: "decorate",
	jakne: "rocket",
	jalge: "result",
	jalna: "starch",
	jalra: "cockroach",
	jamfu: "foot",
	jamna: "war",
	janbe: "bell",
	janco: "shoulder",
	janli: "collide",
	jansu: "diplomat",
	janta: "account",
	jarbu: "suburb",
	jarco: "show",
	jarki: "narrow",
	jaspu: "passport",
	jatna: "captain",
	javni: "rule",
	jbama: "bomb",
	jbari: "berry",
	jbena: "born",
	jbera: "borrow",
	jbini: "between",
	jdari: "firm",
	jdice: "decide",
	jdika: "decrease",
	jdima: "price",
	jdini: "money",
	jduli: "jelly",
	jecta: "polity",
	jeftu: "week",
	jegvo: "Jehovist",
	jelca: "burn",
	jemna: "gem",
	jenca: "shock",
	jendu: "axle",
	jenmi: "army",
	jerna: "earn",
	jersi: "chase",
	jerxo: "Algerian",
	jesni: "needle",
	jetce: "jet",
	jetnu: "true",
	jgalu: "claw",
	jganu: "angle",
	jgari: "grasp",
	jgena: "knot",
	jgina: "gene",
	jgira: "pride",
	jgita: "guitar",
	jibni: "near",
	jibri: "job",
	jicla: "stir",
	jicmu: "basis",
	jijnu: "intuit",
	jikca: "socialize",
	jikru: "liquor",
	jilka: "alkali",
	jilra: "jealous",
	jimca: "branch",
	jimpe: "understand",
	jimte: "limit",
	jinci: "shears",
	jinga: "win",
	jinku: "vaccine",
	jinme: "metal",
	jinru: "immerse",
	jinsa: "clean",
	jinto: "well; spring",
	jinvi: "opine",
	jinzi: "innate property",
	jipci: "chicken",
	jipno: "tip",
	jirna: "horn",
	jisra: "juice",
	jitfa: "false",
	jitro: "control",
	jivbu: "weave",
	jivna: "compete",
	jmaji: "gather",
	jmifa: "shoal",
	jmina: "add",
	jmive: "live",
	jordo: "Jordanian",
	jorne: "joined",
	jubme: "table",
	judri: "address",
	jufra: "sentence",
	jukni: "spider",
	jukpa: "cook",
	julne: "net",
	jundi: "attentive",
	jungo: "Chinese",
	junla: "clock",
	junri: "serious",
	junta: "weight",
	jurme: "germ",
	jursa: "severe",
	jutsi: "species",
	juxre: "clumsy",
	jvinu: "view",
	kabri: "cup",
	kacma: "camera",
	kadno: "Canadian",
	kafke: "cough",
	kagni: "company",
	kajde: "warn",
	kajna: "shelf",
	kakne: "be able to",
	kakpa: "dig",
	kalci: "feces",
	kalri: "open",
	kalsa: "chaotic",
	kalte: "hunt",
	kamju: "column",
	kamni: "committee",
	kampu: "common",
	kanba: "goat",
	kancu: "count",
	kandi: "dim",
	kanji: "calculate",
	kanla: "eye",
	kanro: "healthy",
	kansa: "with",
	kantu: "quantum",
	kanxe: "conjunction",
	karbi: "compare",
	karce: "car",
	karda: "card",
	kargu: "costly",
	karli: "collar",
	karni: "journal",
	katna: "cut",
	kavbu: "capture",
	kecti: "pity",
	kelci: "play",
	kelvo: "kelvin",
	kenra: "cancer",
	kensa: "outer space",
	kerfa: "hair",
	kerlo: "ear",
	ketco: "South American",
	kevna: "cavity",
	kibro: "internet",
	kicne: "cushion",
	kijno: "oxygen",
	kilto: "1000",
	kinda: "kind of",
	kinli: "sharp",
	kisto: "Pakistani",
	klaji: "street",
	klaku: "weep",
	klama: "go",
	klani: "quantity",
	klesi: "class",
	klina: "clear",
	kliru: "chlorine",
	kliti: "clay",
	klupe: "screw",
	kluza: "loose",
	kobli: "cabbage",
	kojna: "corner",
	kolme: "coal",
	komcu: "comb",
	konju: "cone",
	korbi: "edge",
	korcu: "bent",
	korka: "cork",
	kosta: "coat",
	kramu: "acre",
	krasi: "source",
	krati: "represent",
	krefu: "repetition",
	krici: "believe",
	krili: "crystal",
	krinu: "reason",
	krixa: "cry out",
	kruca: "intersect",
	kruji: "cream",
	kruvi: "curve",
	kubli: "cube",
	kucli: "curious",
	kufra: "comfort",
	kukte: "delicious",
	kulnu: "culture",
	kumfa: "room",
	kumte: "camel",
	kunra: "mineral",
	kunti: "empty",
	kurfa: "square",
	kurji: "take care of",
	kurki: "bitter",
	kuspe: "range",
	kusru: "cruel",
	labno: "wolf",
	lacpu: "pull",
	lacri: "rely",
	ladru: "milk",
	lafti: "lift",
	lakne: "probable",
	lakse: "wax",
	lalxu: "lake",
	lamji: "adjacent",
	lanbi: "protein",
	lanci: "flag",
	lanka: "basket",
	lanli: "analyze",
	lanme: "sheep",
	lante: "can",
	lanxe: "balance",
	lanzu: "family",
	larcu: "art",
	lasna: "fasten",
	lastu: "brass",
	latmo: "Latin",
	latna: "lotus",
	lazni: "lazy",
	lebna: "take",
	lenjo: "lens",
	lenku: "cold",
	lerci: "late",
	lerfu: "letteral",
	libjo: "Libyan",
	lidne: "precede",
	lifri: "experience",
	lijda: "religion",
	limna: "swim",
	lindi: "lightning",
	linji: "line",
	linsi: "chain",
	linto: "lightweight",
	lisri: "story",
	liste: "list",
	litce: "liter",
	litki: "liquid",
	litru: "travel",
	livga: "liver",
	livla: "fuel",
	logji: "logic",
	lojbo: "Lojbanic",
	loldi: "floor",
	lorxu: "fox",
	lubno: "Lebanese",
	lujvo: "lujvo",
	lumci: "wash",
	lunbe: "bare",
	lunra: "lunar",
	lunsa: "condense",
	mabla: "derogative",
	mabru: "mammal",
	macnu: "manual",
	makcu: "mature",
	makfa: "magic",
	maksi: "magnet",
	malsi: "temple",
	mamta: "mother",
	manci: "wonder",
	manfo: "uniform",
	manku: "dark",
	manri: "reference",
	mansa: "satisfy",
	manti: "ant",
	mapku: "cap",
	mapni: "cotton",
	mapti: "fit",
	marbi: "shelter",
	marce: "vehicle",
	marde: "ethics",
	margu: "mercury",
	marji: "material",
	marna: "hemp",
	marxa: "mash",
	masno: "slow",
	masti: "month",
	matci: "mat",
	matli: "linen",
	matne: "butter",
	matra: "motor",
	mavji: "oats",
	maxri: "wheat",
	mebri: "brow",
	// megdo: "1e6",
	mekso: "mekso",
	melbi: "beautiful",
	meljo: "Malaysian",
	menli: "mind",
	mensi: "sister",
	mentu: "minute",
	merko: "American",
	merli: "measure",
	mexno: "Mexican",
	midju: "middle",
	mifra: "code",
	mikce: "doctor",
	// mikri: "1e-6",
	milti: ".001",
	milxe: "mild",
	minde: "command",
	minji: "machine",
	minli: "mile",
	minra: "reflect",
	mintu: "same",
	mipri: "secret",
	mirli: "deer",
	misno: "famous",
	misro: "Egyptian",
	mitre: "meter",
	mixre: "mixture",
	mlana: "side",
	mlatu: "cat",
	mleca: "less",
	mledi: "mold",
	mluni: "satellite",
	mokca: "point",
	moklu: "mouth",
	molki: "mill",
	molro: "mole",
	morji: "remember",
	morko: "Moroccan",
	morna: "pattern",
	morsi: "dead",
	mosra: "friction",
	mraji: "rye",
	mrilu: "mail",
	mruli: "hammer",
	mucti: "immaterial",
	mudri: "wood",
	mukti: "motive",
	mulno: "complete",
	munje: "universe",
	mupli: "example",
	murse: "glimmering",
	murta: "curtain",
	muslo: "Islamic",
	mutce: "much",
	muvdu: "move",
	muzga: "museum",
	nabmi: "problem",
	nakni: "male",
	nalci: "wing",
	namcu: "number",
	nanba: "bread",
	nanca: "year",
	nandu: "difficult",
	nanla: "boy",
	nanmu: "man",
	// nanvi: "1e-9",
	narge: "nut",
	narju: "orange",
	natfe: "deny",
	natmi: "nation",
	navni: "neon",
	naxle: "canal",
	nazbi: "nose",
	nejni: "energy",
	nelci: "like",
	nenri: "in",
	nibli: "necessitate",
	nicte: "night",
	nikle: "nickel",
	nilce: "furniture",
	nimre: "citrus",
	ninmu: "woman",
	nirna: "nerve",
	nitcu: "need",
	nivji: "knit",
	nixli: "girl",
	nobli: "noble",
	notci: "message",
	nukni: "magenta",
	nupre: "promise",
	nurma: "rural",
	nutli: "neutral",
	nuzba: "news",
	pacna: "hope",
	pagbu: "part",
	pagre: "pass through",
	pajni: "judge",
	palci: "evil",
	palku: "pants",
	palne: "tray",
	palpi: "palpate",
	palta: "plate",
	pambe: "pump",
	panci: "odor",
	pandi: "punctuate",
	panje: "sponge",
	panka: "park",
	panlo: "slice",
	panpi: "peace",
	panra: "parallel",
	pante: "protest",
	panzi: "offspring",
	papri: "page",
	parbi: "ratio",
	pastu: "robe",
	patfu: "father",
	patlu: "potato",
	patxu: "pot",
	pelji: "paper",
	pelxu: "yellow",
	pemci: "poem",
	penbi: "pen",
	pencu: "touch",
	pendo: "friend",
	penmi: "meet",
	pensi: "think",
	perli: "pear",
	pesxu: "paste",
	// petso: "1e15",
	pezli: "leaf",
	// picti: "1e-12",
	pijne: "pin",
	pikci: "beg",
	pikta: "ticket",
	pilji: "multiply",
	pilka: "crust",
	pilno: "use",
	pimlu: "feather",
	pinca: "urine",
	pindi: "poor",
	pinfu: "prisoner",
	pinji: "penis",
	pinka: "comment",
	pinsi: "pencil",
	pinta: "level",
	pinxe: "drink",
	pipno: "piano",
	pixra: "picture",
	plana: "plump",
	platu: "plan",
	pleji: "pay",
	plibu: "pubic",
	plini: "planet",
	plipe: "leap",
	plise: "apple",
	plita: "plane",
	plixa: "plow",
	pluja: "complicated",
	pluka: "pleasant",
	pluta: "route",
	polje: "fold",
	polno: "Polynesian",
	ponjo: "Japanese",
	ponse: "own",
	porpi: "break",
	porsi: "sequence",
	porto: "Portuguese",
	prali: "profit",
	prami: "love",
	prane: "perfect",
	preja: "spread",
	prenu: "person",
	preti: "question",
	prije: "wise",
	prina: "print",
	pritu: "right",
	prosa: "prose",
	pruce: "process",
	pruni: "elastic",
	pruxi: "spirit",
	pulce: "dust",
	pulji: "police",
	pulni: "pulley",
	punji: "put",
	punli: "swelling",
	purci: "past",
	purdi: "garden",
	purmo: "powder",
	racli: "sane",
	ractu: "rabbit",
	radno: "radian",
	rafsi: "affix",
	ragve: "across",
	rakso: "Iraqi",
	raktu: "trouble",
	ralci: "delicate",
	ralju: "principal",
	ralte: "retain",
	randa: "yield",
	rango: "organ",
	ranji: "continue",
	ranmi: "myth",
	ransu: "bronze",
	ranti: "soft",
	ranxi: "irony",
	rapli: "repeat",
	rarna: "natural",
	ratcu: "rat",
	ratni: "atom",
	rebla: "tail",
	rectu: "meat",
	remna: "human",
	renro: "throw",
	renvi: "survive",
	respa: "reptile",
	ricfu: "rich",
	rigni: "disgusting",
	rijno: "silver",
	rilti: "rhythm",
	rimni: "rhyme",
	rinci: "drain",
	rinju: "restrain",
	rinka: "cause",
	rinsa: "greet",
	rirci: "rare",
	rirni: "parent",
	rirxe: "river",
	rismi: "rice",
	risna: "heart",
	ritli: "rite",
	rivbi: "avoid",
	rokci: "rock",
	romge: "chrome",
	ropno: "European",
	rorci: "procreate",
	rotsu: "thick",
	rozgu: "rose",
	ruble: "weak",
	rufsu: "rough",
	runme: "melt",
	runta: "dissolve",
	rupnu: "dollar",
	rusko: "Russian",
	rutni: "artifact",
	sabji: "provide",
	sabnu: "cabin",
	sacki: "match",
	saclu: "decimal",
	sadjo: "Saudi",
	sakci: "suck",
	sakli: "slide",
	sakta: "sugar",
	salci: "celebrate",
	salpo: "slope",
	salta: "salad",
	samcu: "cassava",
	sampu: "simple",
	sance: "sound",
	sanga: "sing",
	sanji: "conscious",
	sanli: "stand",
	sanmi: "meal",
	sanso: "sauce",
	santa: "umbrella",
	sarcu: "necessary",
	sarji: "support",
	sarlu: "spiral",
	sarxe: "harmonious",
	saske: "science",
	satci: "exact",
	satre: "stroke",
	savru: "noise",
	sazri: "operate",
	sefta: "surface",
	selci: "cell",
	selfu: "serve",
	semto: "Semitic",
	senci: "sneeze",
	senpi: "doubt",
	senta: "layer",
	senva: "dream",
	sepli: "apart",
	serti: "stairs",
	setca: "insert",
	sevzi: "self",
	sfani: "fly (insect)",
	sfasa: "punish",
	sfofa: "sofa",
	sfubu: "dive",
	siclu: "whistle",
	sicni: "coin",
	sidbo: "idea",
	sidju: "help",
	sigja: "cigar",
	silka: "silk",
	silna: "salt",
	simlu: "seem",
	simsa: "similar",
	simxu: "mutual",
	since: "snake",
	sinma: "esteem",
	sinso: "sine",
	sinxa: "sign",
	sipna: "sleep",
	sirji: "straight",
	sirxo: "Syrian",
	sisku: "seek",
	sisti: "cease",
	sitna: "cite",
	sivni: "private",
	skaci: "skirt",
	skami: "computer",
	skapi: "pelt",
	skari: "color",
	skicu: "describe",
	skiji: "ski",
	skina: "cinema",
	skori: "cord",
	skoto: "Scottish",
	skuro: "groove",
	slabu: "familiar",
	slaka: "syllable",
	slami: "acid",
	slanu: "cylinder",
	slari: "sour",
	slasi: "plastic",
	sligu: "solid",
	slilu: "oscillate",
	sliri: "sulfur",
	slovo: "Slavic",
	sluji: "muscle",
	sluni: "onion",
	smacu: "mouse",
	smadi: "guess",
	smaji: "quiet",
	smani: "monkey",
	smoka: "sock",
	smuci: "spoon",
	smuni: "meaning",
	snada: "succeed",
	snanu: "south",
	snidu: "second",
	snime: "snow",
	snipa: "sticky",
	snuji: "sandwich",
	snura: "secure",
	snuti: "accidental",
	sobde: "soya",
	sodna: "sodium",
	sodva: "soda",
	softo: "Soviet",
	solji: "gold",
	solri: "solar",
	sombo: "sow",
	sonci: "soldier",
	sorcu: "store",
	sorgu: "sorghum",
	sovda: "egg",
	spaji: "surprise",
	spali: "polish",
	spano: "Spanish",
	spati: "plant",
	speni: "married",
	spisa: "piece",
	spita: "hospital",
	spofu: "broken",
	spoja: "explode",
	spuda: "reply",
	sputu: "spit",
	sraji: "vertical",
	sraku: "scratch",
	sralo: "Australian",
	srana: "pertain",
	srasu: "grass",
	srera: "err",
	srito: "Sanskrit",
	sruma: "assume",
	sruri: "surround",
	stace: "honest",
	stagi: "vegetable",
	staku: "ceramic",
	stali: "remain",
	stani: "stalk",
	stapa: "step",
	stasu: "soup",
	stati: "talent",
	steba: "frustration",
	steci: "specific",
	stedu: "head",
	stela: "lock",
	stero: "steradian",
	stici: "west",
	stidi: "suggest",
	stika: "adjust",
	stizu: "chair",
	stodi: "constant",
	stuna: "east",
	stura: "structure",
	stuzi: "place",
	sucta: "abstract",
	sudga: "dry",
	sufti: "hoof",
	suksa: "sudden",
	sumji: "sum",
	sumne: "smell",
	sumti: "argument",
	sunga: "garlic",
	sunla: "wool",
	surla: "relax",
	sutra: "fast",
	tabno: "carbon",
	tabra: "trumpet",
	tadji: "method",
	tadni: "study",
	tagji: "snug",
	talsa: "challenge",
	tamca: "tomato",
	tamji: "thumb",
	tamne: "cousin",
	tanbo: "board",
	tance: "tongue",
	tanjo: "tangent",
	tanko: "tobacco",
	tanru: "tanru",
	tansi: "pan",
	tanxe: "box",
	tapla: "tile",
	tarbi: "embryo",
	tarci: "star",
	tarla: "tar",
	tarmi: "shape",
	tarti: "behave",
	taske: "thirst",
	tatpi: "tired",
	tatru: "breast",
	tavla: "talk",
	taxfu: "garment",
	tcaci: "custom",
	tcadu: "city",
	tcana: "station",
	tcati: "tea",
	tcena: "stretch",
	tcica: "deceive",
	tcidu: "read",
	tcika: "time of day",
	tcila: "detail",
	tcima: "weather",
	tcini: "situation",
	tcita: "label",
	temci: "time",
	tenfa: "exponential",
	tengu: "texture",
	terdi: "earth",
	terpa: "fear",
	// terto: "1e12",
	tigni: "perform",
	tikpa: "kick",
	tilju: "heavy",
	tinbe: "obey",
	tinci: "tin",
	tinsa: "stiff",
	tirna: "hear",
	tirse: "iron",
	tirxu: "tiger",
	tisna: "fill",
	titla: "sweet",
	tivni: "television broadcaster",
	tixnu: "daughter",
	toknu: "oven",
	toldi: "butterfly",
	tonga: "tone",
	tordu: "short",
	torni: "twist",
	traji: "superlative",
	trano: "nitrogen",
	trati: "taut",
	trene: "train",
	tricu: "tree",
	trina: "attract",
	trixe: "behind",
	troci: "try",
	tsali: "strong",
	tsani: "sky",
	tsapi: "seasoning",
	tsiju: "seed",
	tsina: "stage",
	tubnu: "tube",
	tugni: "agree",
	tujli: "tulip",
	tumla: "land",
	tunba: "sibling",
	tunka: "copper",
	tunlo: "swallow",
	tunta: "poke",
	tuple: "leg",
	turni: "govern",
	tutci: "tool",
	tutra: "territory",
	vacri: "air",
	vajni: "important",
	valsi: "word",
	vamji: "value",
	vamtu: "vomit",
	vanbi: "environment",
	vanci: "evening",
	vanju: "wine",
	vasru: "contain",
	vasxu: "breathe",
	vecnu: "sell",
	venfu: "revenge",
	vensa: "spring",
	verba: "child",
	vibna: "vagina",
	vidni: "monitor",
	vidru: "virus",
	vifne: "fresh",
	vikmi: "excrete",
	viknu: "viscous",
	vimcu: "remove",
	vindu: "poison",
	vinji: "airplane",
	vipsi: "deputy",
	virnu: "brave",
	viska: "see",
	vitci: "irregular",
	vitke: "guest",
	vitno: "permanent",
	vlagi: "vulva",
	vlile: "violent",
	vlina: "alternation",
	vlipa: "powerful",
	vofli: "fly",
	voksa: "voice",
	vorme: "door",
	vraga: "lever",
	vreji: "record",
	vreta: "reclining",
	vrici: "miscellaneous",
	vrude: "virtue",
	vrusi: "taste",
	vukro: "Ukrainian",
	xabju: "inhabit",
	xadba: "half",
	xadni: "body",
	xagji: "hunger",
	xagri: "reed",
	xajmi: "funny",
	xaksu: "use up",
	xalbo: "levity",
	xalka: "alcohol",
	xalni: "panic",
	xamgu: "good",
	xampo: "ampere",
	xamsi: "sea",
	xance: "hand",
	xanka: "nervous",
	xanri: "imaginary",
	xanto: "elephant",
	xarci: "weapon",
	xarju: "pig",
	xarnu: "stubborn",
	xasli: "donkey",
	xasne: "sweat",
	xatra: "letter",
	// xatsi: "1e-18",
	xazdo: "Asiatic",
	xebni: "hate",
	xebro: "Hebrew",
	xecto: "100",
	xedja: "jaw",
	xekri: "black",
	xelso: "Greek",
	xendo: "kind",
	xenru: "regret",
	// xexso: "1e18",
	xindo: "Hindi",
	xinmo: "ink",
	xirma: "horse",
	xislu: "wheel",
	xispo: "Hispanic",
	xlali: "bad",
	xlura: "influence",
	xotli: "hotel",
	xrabo: "Arabic",
	xrani: "injure",
	xriso: "Christian",
	xruba: "buckwheat",
	xruki: "turkey",
	xrula: "flower",
	xruti: "return oneself",
	xukmi: "chemical",
	xunre: "red",
	xurdo: "Urdu",
	xusra: "assert",
	xutla: "smooth",
	zabna: "favorable",
	zajba: "gymnast",
	zalvi: "grind",
	zanru: "approve",
	zarci: "market",
	zargu: "buttock",
	zasni: "temporary",
	zasti: "exist",
	zbabu: "soap",
	zbani: "bay",
	zbasu: "make",
	zbepi: "pedestal",
	zdani: "house",
	zdile: "amusing",
	zekri: "crime",
	zenba: "increase",
	// zepti: "1e-21",
	// zetro: "1e21",
	zgana: "observe",
	zgike: "music",
	zifre: "free",
	zinki: "zinc",
	zirpu: "purple",
	zivle: "invest",
	zmadu: "more",
	zmiku: "automatic",
	zukte: "act",
	zumri: "maize",
	zungi: "guilt",
	zunle: "left",
	zunti: "interfere",
	zutse: "sit",
	zvati: "at",
};

export function glossFromDefinition(definition: string): string | undefined {
	const m = definition.match(
		/^\$[a-z1-5=_]+\$ (is( an?| some)?|are|acts) (quantity of |amount of )?([\w ]+)(?= of| with| for| to| in| at| toward| involving|\W|$)/,
	);
	if (m && m[4].length < 16) return m[4];
	const m2 = definition.match(
		/^\$[a-z1-5=_]+\$ ([a-z/ ]+)( for| to| in| at| of| with| toward)?[$.]/,
	);
	if (m2) {
		const gloss = m2[1].split("/")[0];
		if (gloss.length < 16) return gloss;
	}
	return undefined;
}

export function getDefinition(word: string): string | undefined {
	return definitions[word];
}

export function glossWord(
	word: string,
	selmaho: string,
): { gloss: string; problem?: boolean } | undefined {
	const short = shortDescriptions[word];
	if (short) return { gloss: short };
	const definition = getDefinition(word);
	if (definition) {
		const gloss = glossFromDefinition(definition);
		if (gloss) return { gloss };
	}
	if (selmaho !== "BRIVLA") {
		return undefined;
	}

	const analysis = analyseBrivla(word);
	console.log({ analysis });
	if (analysis.success && analysis.type.endsWith("LUJVO")) {
		const partGlosses = getVeljvo(word).map((x) => glossWord(x, "BRIVLA"));
		const parts = partGlosses.map((x) => (x && "gloss" in x ? x.gloss : ""));
		if (parts.every((x) => x)) {
			return { gloss: parts.join("-") };
		}
	} else if (!analysis.success) {
		if (/^[^aeiou][aeiou][^aeiou]/.test(word)) {
			const insertY = `${word.slice(0, 3)}y${word.slice(3)}`;
			const yAnalysis = analyseBrivla(insertY);
			if (yAnalysis.success && yAnalysis.type.endsWith("LUJVO")) {
				return {
					problem: true,
					gloss: `falls apart (did you mean ${insertY}?)`,
				};
			}
		} else {
			const ba = `ba${word}`;
			const baAnalysis = analyseBrivla(ba);

			if (baAnalysis.success && baAnalysis.type.endsWith("LUJVO")) {
				return {
					problem: true,
					gloss: `invalid: "ba${word}" would be a lujvo`,
				};
			}
		}
		return { problem: true, gloss: analysis.problem.replace(/:? \{[^{}]*\}$/, "") };
	}
}
